### ISSUE TITLE
可以不抓包跳过健康码上传直接签到吗

### ISSUE THREAD

**Issue by muzisunqi123** [PilyziFox/XYB_Auto_Sign_Pandemic#1]
可以不抓包跳过健康码上传直接签到吗
谢谢

**Comment by PilyziFox** [comment]
> [跳过健康码签到的方式目前技术不可行，而且跳过健康码也是有风险的](https://github.com/TiyaAnlite/xybAutoSign/issues/6#issuecomment-1108654124)

正如 [`TiyaAnlite`](https://github.com/TiyaAnlite) 所述，无法实现跳过。我所写这个程序也只能做到**上传相应健康信息**再进行签到。此外抓包是为了获取openId和unionId，用以进行之后的操作的。虽然校友邦有账号登录的方法，但是因为没有接触过，所以没有实现。
